Implemented canary deployment successfully and automated rollback in end to end cicd pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,6 +76,7 @@ jobs:
 
 
   deploy:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     needs: build-and-push
 
@@ -97,16 +98,48 @@ jobs:
             --name $AKS_CLUSTER_NAME \
             --overwrite-existing
 
-      - name: Deploy image to AKS
+      - name: Deploy new version to Canary
+        run: |
+          kubectl set image deployment/safedeploy-canary \
+            safedeploy-app=$ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
+
+      - name: Wait for Canary rollout
+        run: |
+          kubectl rollout status deployment/safedeploy-canary --timeout=180s
+
+      - name: Run Canary Health Check
+        id: canary-health
+        run: |
+          kubectl run canary-health-check \
+            --rm \
+            -i \
+            --restart=Never \
+            --image=curlimages/curl \
+            -- curl -fsS http://safedeploy-canary-service/health
+
+      - name: Promote Canary to Stable
+        if: steps.canary-health.outcome == 'success'
         run: |
           kubectl set image deployment/safedeploy-app \
             safedeploy-app=$ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
 
-      - name: Wait for deployment rollout
-        run: |
           kubectl rollout status deployment/safedeploy-app --timeout=180s
 
-      - name: Verify deployment
+      - name: Rollback Canary
+        if: steps.canary-health.outcome == 'failure'
+        run: |
+          echo "Canary health check failed. Rolling back..."
+          kubectl rollout undo deployment/safedeploy-canary
+          kubectl rollout status deployment/safedeploy-canary --timeout=180s
+
+      - name: Fail Deployment
+        if: steps.canary-health.outcome == 'failure'
+        run: |
+          echo "Canary deployment failed. Stable version was NOT promoted."
+          exit 1
+
+      - name: Verify Deployment
         run: |
           kubectl get deployment safedeploy-app
+          kubectl get deployment safedeploy-canary
           kubectl get pods -l app=safedeploy-app
